// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Plainion.AppFw.Wpf.Infrastructure")]
[assembly: AssemblyProductAttribute("Plainion.AppFw.Wpf")]
[assembly: AssemblyDescriptionAttribute("Plainion.AppFw.Wpf")]
[assembly: AssemblyCopyrightAttribute("Copyright @ 2017")]
[assembly: AssemblyVersionAttribute("3.0.0")]
[assembly: AssemblyFileVersionAttribute("3.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Plainion.AppFw.Wpf.Infrastructure";
        internal const System.String AssemblyProduct = "Plainion.AppFw.Wpf";
        internal const System.String AssemblyDescription = "Plainion.AppFw.Wpf";
        internal const System.String AssemblyCopyright = "Copyright @ 2017";
        internal const System.String AssemblyVersion = "3.0.0";
        internal const System.String AssemblyFileVersion = "3.0.0";
    }
}
